//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.02 at 08:28:00 AM IST 
//


package com.accenture.abms.datacollection.recordsmatch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompareFields complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompareFields">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="compare-field" type="{http://recordsmatch.datacollection.abms.accenture.com}CompareField" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="custom-comapre" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompareFields", propOrder = {
    "compareField"
})
public class CompareFields {

    @XmlElement(name = "compare-field")
    protected List<CompareField> compareField;
    @XmlAttribute(name = "custom-comapre")
    protected String customComapre;

    /**
     * Gets the value of the compareField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compareField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompareField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompareField }
     * 
     * 
     */
    public List<CompareField> getCompareField() {
        if (compareField == null) {
            compareField = new ArrayList<CompareField>();
        }
        return this.compareField;
    }

    /**
     * Gets the value of the customComapre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomComapre() {
        return customComapre;
    }

    /**
     * Sets the value of the customComapre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomComapre(String value) {
        this.customComapre = value;
    }

}
