//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.02 at 08:28:00 AM IST 
//


package com.accenture.abms.datacollection.recordsmatch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accenture.abms.datacollection.recordsmatch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accenture.abms.datacollection.recordsmatch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordMatch }
     * 
     */
    public RecordMatch createRecordMatch() {
        return new RecordMatch();
    }

    /**
     * Create an instance of {@link RecordConfig }
     * 
     */
    public RecordConfig createRecordConfig() {
        return new RecordConfig();
    }

    /**
     * Create an instance of {@link DisplayFields }
     * 
     */
    public DisplayFields createDisplayFields() {
        return new DisplayFields();
    }

    /**
     * Create an instance of {@link DisplayField }
     * 
     */
    public DisplayField createDisplayField() {
        return new DisplayField();
    }

    /**
     * Create an instance of {@link CompareFields }
     * 
     */
    public CompareFields createCompareFields() {
        return new CompareFields();
    }

    /**
     * Create an instance of {@link CompareField }
     * 
     */
    public CompareField createCompareField() {
        return new CompareField();
    }

}
