//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.02 at 08:28:00 AM IST 
//


package com.accenture.abms.datacollection.recordsmatch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="compare-fileds" type="{http://recordsmatch.datacollection.abms.accenture.com}CompareFields"/>
 *         &lt;element name="display-fileds" type="{http://recordsmatch.datacollection.abms.accenture.com}DisplayFields"/>
 *       &lt;/sequence>
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordConfig", propOrder = {
    "compareFileds",
    "displayFileds"
})
public class RecordConfig {

    @XmlElement(name = "compare-fileds", required = true)
    protected CompareFields compareFileds;
    @XmlElement(name = "display-fileds", required = true)
    protected DisplayFields displayFileds;
    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "target")
    protected String target;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the compareFileds property.
     * 
     * @return
     *     possible object is
     *     {@link CompareFields }
     *     
     */
    public CompareFields getCompareFileds() {
        return compareFileds;
    }

    /**
     * Sets the value of the compareFileds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompareFields }
     *     
     */
    public void setCompareFileds(CompareFields value) {
        this.compareFileds = value;
    }

    /**
     * Gets the value of the displayFileds property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayFields }
     *     
     */
    public DisplayFields getDisplayFileds() {
        return displayFileds;
    }

    /**
     * Sets the value of the displayFileds property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayFields }
     *     
     */
    public void setDisplayFileds(DisplayFields value) {
        this.displayFileds = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
